import React from "react";

const Privacypolicy = () => {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-800 py-12 px-6 md:px-12 lg:px-24 md:pt-28">
      <h1 className="text-4xl font-bold mb-6 text-center">Privacy Policy</h1>
      <p className="mb-4">Effective Date: <strong>August 3, 2025</strong></p>
      <p className="mb-4">Company Name: <strong>AI EVOKED (OPC) Private Limited</strong></p>
      <p className="mb-6">
        Website: <a href="https://aievoked.com" className="text-black">https://aievoked.com</a>
      </p>
      <p className="mb-6">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
      </p>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Interpretation and Definitions</h2>
        <h3 className="font-semibold mb-1">Interpretation</h3>
        <p className="mb-2">
          The words of which the initial letter is capitalised have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="font-semibold mb-1">Definitions</h3>
        <p className="mb-2">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc list-inside mb-2 space-y-1">
          <li><strong>Account:</strong> a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate:</strong> an entity that controls, is controlled by or is under common control with a party.</li>
          <li><strong>Company:</strong> refers to AI EVOKED (OPC) Private Limited.</li>
          <li><strong>Cookies:</strong> small files placed on Your computer or device by a website.</li>
          <li><strong>Country:</strong> Delhi, India.</li>
          <li><strong>Device:</strong> any device that can access the Service.</li>
          <li><strong>Personal Data:</strong> any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service:</strong> refers to the Website.</li>
          <li><strong>Service Provider:</strong> third-party companies or individuals employed by the Company to facilitate the Service.</li>
          <li><strong>Third-party Social Media Service:</strong> any website or social network through which a User can log in or create an account.</li>
          <li><strong>Usage Data:</strong> data collected automatically, generated by use of the Service.</li>
          <li><strong>Website:</strong> AI EVOKED, accessible from AIEVOKED.COM.</li>
          <li><strong>You:</strong> the individual accessing or using the Service.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Collecting and Using Your Personal Data</h2>
        <h3 className="font-semibold mb-1">Types of Data Collected</h3>
        <p className="mb-2"><strong>Personal Data:</strong> Email, name, phone number, Usage Data.</p>
        <p className="mb-2"><strong>Usage Data:</strong> Device info, IP address, browser type, pages visited, time spent, etc.</p>
        <p className="mb-2"><strong>Information from Third-Party Social Media Services:</strong> Google, Facebook, Instagram, Twitter, LinkedIn.</p>
        <p className="mb-2"><strong>Tracking Technologies and Cookies:</strong> Cookies, Web Beacons, Session & Persistent Cookies.</p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Use of Your Personal Data</h2>
        <p className="mb-2">
          We use Your Personal Data to provide and maintain our Service, manage your account, contact You, provide news and offers, manage requests, conduct business transfers, and for other purposes like analytics and improving our Service.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Retention of Your Personal Data</h2>
        <p className="mb-2">
          Your Personal Data is retained only as long as necessary to comply with legal obligations, resolve disputes, and enforce agreements.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Your Rights</h2>
        <p className="mb-2">You have the right to delete or request deletion of your Personal Data, update your information, and control sharing through Third-Party Social Media Services.</p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Security of Your Personal Data</h2>
        <p className="mb-2">We strive to use commercially acceptable means to protect Your Personal Data, but cannot guarantee 100% security.</p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Children's Privacy</h2>
        <p className="mb-2">Our Service does not address anyone under 13 years. We do not knowingly collect personal info from children under 13.</p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Links to Other Websites</h2>
        <p className="mb-2">Our Service may contain links to other websites. We have no control over their content or privacy practices.</p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Changes to this Privacy Policy</h2>
        <p className="mb-2">We may update this Privacy Policy from time to time. Changes are effective when posted on this page.</p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">Contact Us</h2>
        <p>If you have any questions, contact us at: <a href="mailto:Contact@aievoked.com" className="text-purple-600 underline">Contact@aievoked.com</a></p>
      </section>
    </div>
  );
};

export default Privacypolicy;
